version: '3'

services:
  mongodb:
    image: mongo:4.2
    container_name: star-mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db:cached
    ports:
        - 27017:27017
    networks:
      - star-dev

networks:
  star-dev:
    external: true
