version: '3'

services:
  api:
    container_name: star-api
    image: node:12
    environment:
      - MONGO_URL=mongodb://mongodb:27017/star
      - NODE_ENV=development
      - HOSTNAME=star-api
    command: sleep infinity
    user: 1000:1000
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - ./api:/opt/app:delegated
      - ./dev-files/.bashrc:/home/node/.bashrc
      - $HOME/.bash_history:/home/node/.bash_history
    networks:
      - star-dev

networks:
  star-dev:
    external: true
