version: '3'

services:
  api:
    container_name: star-api
    image: node:12
    environment:
      - MONGO_URL=mongodb://mongodb:27017/star
      - NODE_ENV=development
      - HOSTNAME=star-api
    command: sleep infinity
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - ./api:/opt/app:delegated
      - ./dev-files/.bashrc:/root/.bashrc
      - $HOME/.bash_history:/root/.bash_history
    depends_on:
      - mongodb

  ui:
    container_name: star-ui
    image: star-ui
    build: ./ui
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000
    ports:
      - 3000:80

  mongodb:
      image: mongo:4.2
      container_name: star-mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
