version: '3'

services:
  api:
    container_name: star-api
    image: star-api
    build: .
    environment:
      - MONGO_URL=mongodb://mongodb:27017/star
      - NODE_ENV=development
    ports:
      - 8000:8000
    volumes:
      - ./api:/opt/app
    depends_on:
      - mongodb

  ui:
    container_name: star-ui
    image: star-ui
    build: .
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:8000
    ports:
      - 80:8000
    volumes:
      - ./ui:/opt/app

  mongodb:
      image: mongo:4.2
      container_name: star-mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
